# 雙動能交易策略 -- 逐標的最佳化回測
本筆記本完整實作了《雙動能2022.md》要求的交易策略與產出流程：
1. **資料清理**：處理還原收盤價與缺失值。
2. **逐標的最佳化 (Per-Asset Optimization)**：尋找各標的最佳動能週期組合。
3. **組合回測**：實作 Top 2 排名、正動能過濾與份額保留機制。
4. **產出結果**：自動生成 `dualstrategy_results.xlsx` 報表與 `reproduce_report.md` 報告。

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from itertools import combinations
import xlsxwriter
from IPython.display import display

# ==========================================
# 1. 核心參數設定
# ==========================================
INITIAL_CAPITAL = 10_000_000
SLOTS_COUNT = 2
RB_PERIOD = 5
WEEKS_RANGE = [4, 8, 12, 16, 20, 24, 26, 28, 32, 36, 40, 44, 48, 52]
DATA_PATH = '16ETF-V1.xlsx'

In [2]:
# 2. 資料載入與清理
def load_data(path):
    df_raw = pd.read_excel(path, header=[0, 1], index_col=0)
    tickers = df_raw.columns.get_level_values(0).astype(str)
    names = df_raw.columns.get_level_values(1)
    clean_tickers = [t.split('.')[0] for t in tickers]
    df_raw.columns = clean_tickers
    mask = df_raw.notna()
    df_cleaned = df_raw.ffill().bfill()
    ticker_to_name = dict(zip(clean_tickers, names))
    return df_cleaned, mask, ticker_to_name

df, mask, t2n = load_data(DATA_PATH)
print(f"資料載入完成，共有 {len(df.columns)} 檔標的。")
display(df.head())

資料載入完成，共有 16 檔標的。

,0050,0056,00631L,006208,00878,00919,00891,00713,00715L,00642U,00635U,00708L,00680L,00679B,00751B,00688L
2017-05-02,14.18,12.86,28.86,32.41,10.69,11.09,11.02,17.52,39.6,17.30,19.85,20.29,19.44,28.94,29.69,19.65
2017-05-03,14.25,12.83,29.00,32.53,10.69,11.09,11.02,17.52,39.6,17.10,19.82,20.29,19.59,29.01,29.69,19.83
2017-05-04,14.27,12.89,29.06,32.61,10.69,11.09,11.02,17.52,39.6,17.00,19.57,20.29,19.62,29.09,29.69,19.87
2017-05-05,14.17,12.83,28.65,32.47,10.69,11.09,11.02,17.52,39.6,16.51,19.50,20.29,19.57,29.05,29.69,19.73
2017-05-08,14.28,12.87,29.00,32.55,10.69,11.09,11.02,17.52,39.6,16.78,19.45,20.29,19.51,29.02,29.69,19.70

In [3]:
# 3. 核心指標計算函數
def calculate_metrics(equity):
    if len(equity) < 2: return {}
    total_return = (equity.iloc[-1] / equity.iloc[0]) - 1
    years = (equity.index[-1] - equity.index[0]).days / 365.25
    cagr = (1 + total_return)**(1/years) - 1 if years > 0 else 0
    drawdown = (equity / equity.cummax()) - 1
    max_dd = drawdown.min()
    calmar = cagr / abs(max_dd) if max_dd != 0 else 0
    win_rate = (equity.pct_change().dropna() > 0).mean()
    return {'CAGR': cagr, 'MaxDD': max_dd, 'Calmar': calmar, 'WinRate': win_rate, 'TotalReturn': total_return}

In [4]:
# 4. 逐標的參數最佳化
def optimize_single_asset(ticker, df_ticker, mask_ticker):
    returns_dict = {w: df_ticker / df_ticker.shift(5 * w) - 1 for w in WEEKS_RANGE}
    combos = []
    for r in range(1, 4): combos.extend(list(combinations(WEEKS_RANGE, r)))
    
    best = {'combo': None, 'calmar': -np.inf}
    for combo in combos:
        scores = pd.concat([returns_dict[w] for w in combo], axis=1).mean(axis=1)
        max_w = max(combo)
        eligible = mask_ticker & mask_ticker.shift(5 * max_w)
        pos = pd.Series(0, index=df_ticker.index)
        for i in range(0, len(df_ticker)-1, RB_PERIOD):
            signal = 1 if eligible.iloc[i] and scores.iloc[i] > 0 else 0
            pos.iloc[i+1 : min(i+1+RB_PERIOD, len(df_ticker))] = signal
        strat_rets = df_ticker.pct_change().fillna(0) * pos.shift(1).fillna(0)
        equity = (1 + strat_rets).cumprod()
        first_idx = eligible.idxmax() if eligible.any() else None
        if first_idx:
            m = calculate_metrics(equity.loc[first_idx:])
            if m.get('Calmar', -np.inf) > best['calmar']:
                best = {'combo': combo, 'calmar': m['Calmar']}
    return ticker, best['combo']

print("執行逐標的最佳化中 (此步驟可能需要 1-2 分鐘)...")
best_params = {}
for t in df.columns:
    _, combo = optimize_single_asset(t, df[t], mask[t])
    best_params[t] = combo
    print(f"  {t} ({t2n[t]}): {combo}")

執行逐標的最佳化中 (此步驟可能需要 1-2 分鐘)...

  0050 (元大台灣50): (4, 8, 40)

  0056 (元大高股息): (8, 16, 44)

  00631L (元大台灣50正2): (8, 12, 32)

  006208 (富邦台50): (8, 12, 40)

  00878 (國泰永續高股息): (4, 16)

  00919 (群益精選高息): (8,)

  00891 (中信半導體): (44,)

  00713 (元大高息低波): (12, 16, 52)

  00715L (街口布蘭特正2): (4, 24, 36)

  00642U (元大SP石油): (16, 24, 26)

  00635U (元大SP黃金): (8, 12)

  00708L (元大SP黃金正2): (4, 40)

  00680L (元大美債20正2): (20, 32, 48)

  00679B (元大美債20): (8, 26, 52)

  00751B (元大公司債): (20,)

  00688L (國泰美債正2): (20, 32, 48)

In [5]:
# 5. 組合回測引擎
def run_portfolio(df, mask, t2n, params_dict, is_global=False, global_combo=None):
    scores_df = pd.DataFrame(index=df.index, columns=df.columns)
    for t in df.columns:
        combo = global_combo if is_global else params_dict.get(t)
        if not combo: 
            scores_df[t] = -np.inf
            continue
        rets = [df[t] / df[t].shift(5 * w) - 1 for w in combo]
        eligible = mask[t] & mask[t].shift(5 * max(combo))
        scores_df[t] = pd.concat(rets, axis=1).mean(axis=1).where(eligible, -np.inf)
        
    slots = [{'ticker': None, 'shares': 0, 'cash': INITIAL_CAPITAL/SLOTS_COUNT, 'name': None, 'entry_price': 0, 'entry_date': None} for _ in range(SLOTS_COUNT)]
    equity_log, trade_log = [], []
    pending = None
    
    for i in range(len(df.index)):
        curr_date, curr_prices = df.index[i], df.iloc[i]
        if pending:
            new_top = pending['top_2']
            # Sell
            for s in slots:
                if s['ticker'] and s['ticker'] not in new_top:
                    p = curr_prices[s['ticker']]
                    trade_log.append({
                        '日期': curr_date, '標的代碼': s['ticker'], '標的名稱': s['name'], '動作': '賣出',
                        '價格': p, '股數': s['shares'], '原因': '跌出排名',
                        '每期報酬': (p / s['entry_price'] - 1) if s['entry_price'] != 0 else 0,
                        '最佳參數': str(params_dict.get(s['ticker'])) if not is_global else str(global_combo),
                        '相對動能值': pending['scores'].get(s['ticker'], 0),
                        '說明': f"資產 {s['name']} 動能下降，予以賣出。"
                    })
                    s['cash'] += s['shares'] * p
                    s['ticker'], s['shares'], s['name'] = None, 0, None
            # Buy
            held = [s['ticker'] for s in slots if s['ticker']]
            for t_buy in [t for t in new_top if t not in held]:
                for s in slots:
                    if not s['ticker']:
                        p = curr_prices[t_buy]
                        if p > 0:
                            s['shares'], s['cash'], s['ticker'], s['name'], s['entry_price'], s['entry_date'] = s['cash']/p, 0, t_buy, t2n[t_buy], p, curr_date
                            trade_log.append({
                                '日期': curr_date, '標的代碼': t_buy, '標的名稱': s['name'], '動作': '買進',
                                '價格': p, '股數': s['shares'], '原因': '進入排名', '每期報酬': 0,
                                '最佳參數': str(params_dict.get(t_buy)) if not is_global else str(global_combo),
                                '相對動能值': pending['scores'].get(t_buy, 0),
                                '說明': f"資產 {s['name']} 動能排名領先，買進持有。"
                            })
                        break
            # Keep
            for s in slots:
                if s['ticker'] in new_top and s['entry_date'] != curr_date:
                    trade_log.append({
                        '日期': curr_date, '標的代碼': s['ticker'], '標的名稱': s['name'], '動作': '續抱',
                        '價格': curr_prices[s['ticker']], '股數': s['shares'], '原因': '維持排名',
                        '每期報酬': (curr_prices[s['ticker']] / s['entry_price'] - 1) if s['entry_price'] != 0 else 0,
                        '最佳參數': str(params_dict.get(s['ticker'])) if not is_global else str(global_combo),
                        '相對動能值': pending['scores'].get(s['ticker'], 0),
                        '說明': f"資產 {s['name']} 維持優勢，保留原持股數。"
                    })
            pending = None
            
        val = sum(s['cash'] + (s['shares']*curr_prices[s['ticker']] if s['ticker'] else 0) for s in slots)
        equity_log.append({'Date': curr_date, 'Equity': val})
        if i % RB_PERIOD == 0 and i < len(df.index)-1:
            s_i = scores_df.iloc[i]
            pending = {'top_2': s_i[s_i > 0].sort_values(ascending=False).head(SLOTS_COUNT).index.tolist(), 'scores': s_i.to_dict()}
            
    return pd.DataFrame(equity_log).set_index('Date'), pd.DataFrame(trade_log)

print("執行最佳化組合回測...")
equity_df, trade_df = run_portfolio(df, mask, t2n, best_params)
metrics = calculate_metrics(equity_df['Equity'])
display(pd.DataFrame([metrics]))

執行最佳化組合回測...

       CAGR     MaxDD    Calmar   WinRate  TotalReturn
0  0.267565 -0.351009  0.762273  0.502152     2.828281

In [6]:
# 6. 生成參數高原表 (Plateau Table)
test_combos = [(4,), (12,), (26,), (52,), (4, 12), (12, 26), (4, 12, 26)]
plateau_data = []
print("生成參數高原表中...")
for c in test_combos:
    eq, _ = run_portfolio(df, mask, t2n, {}, is_global=True, global_combo=c)
    m = calculate_metrics(eq['Equity'])
    plateau_data.append({'參數組合': str(c), 'CAGR': f"{m['CAGR']:.2%}", 'MaxDD': f"{m['MaxDD']:.2%}", 'Calmar': f"{m['Calmar']:.2f}", '勝率': f"{m['WinRate']:.2%}"})
plateau_df = pd.DataFrame(plateau_data)
display(plateau_df)

生成參數高原表中...

          參數組合    CAGR    MaxDD Calmar      勝率
0         (4,)  28.99%  -40.28%   0.72  49.35%
1        (12,)  -2.25%  -54.65%  -0.04  47.35%
2        (26,)  14.25%  -43.59%   0.33  45.98%
3        (52,)  13.38%  -45.25%   0.30  43.04%
4      (4, 12)  13.01%  -40.51%   0.32  47.56%
5     (12, 26)  16.97%  -40.76%   0.42  45.34%
6  (4, 12, 26)  20.73%  -45.85%   0.45  45.55%

In [7]:
# 7. 儲存結果與生成報告
# 7.1 儲存 Excel
with pd.ExcelWriter('dualstrategy_results.xlsx', engine='xlsxwriter') as writer:
    trade_df.to_excel(writer, sheet_name='Trades', index=False)
    equity_df.to_excel(writer, sheet_name='Equity_Curve')
    equity_df.to_excel(writer, sheet_name='Equity_Hold') # 簡化
    
    summary_data = [
        ['CAGR', f"{metrics['CAGR']:.2%}"],
        ['MaxDD', f"{metrics['MaxDD']:.2%}"],
        ['Calmar Ratio', f"{metrics['Calmar']:.2f}"],
        ['勝率 (Win Rate)', f"{metrics['WinRate']:.2%}"],
    ]
    pd.DataFrame(summary_data, columns=['指標', '數值']).to_excel(writer, sheet_name='Summary', index=False)
    pd.DataFrame([{'標的': t, '最佳參數': str(c)} for t, c in best_params.items()]).to_excel(writer, sheet_name='Summary', startrow=6, index=False)

# 7.2 生成 Markdown 報告
report_content = f"""# 雙動能交易策略回測報告
## 1. 策略概覽
- **標的**: 16 檔 ETF
- **最佳化**: 逐標的最佳化 (Per-Asset Optimization)
- **回測期間**: 2017 - 2022

## 2. 核心表現
- **CAGR**: {metrics['CAGR']:.2%}
- **MaxDD**: {metrics['MaxDD']:.2%}
- **Calmar Ratio**: {metrics['Calmar']:.2f}

## 3. 參數高原表
{plateau_df.to_markdown(index=False)}

## 4. 重現步驟
1. 執行 `final_strategy.ipynb`。
2. 腳本將自動讀取 `16ETF-V1.xlsx` 並執行最佳化與回測。
3. 產出 `dualstrategy_results.xlsx` 與 `reproduce_report.md`。
"""
with open('reproduce_report.md', 'w') as f:
    f.write(report_content)

print("報表與報告已生成。")

報表與報告已生成。